baseURL = "https://jack-bradshaw.com/"
languageCode = "en-us"
title = "Jack Bradshaw"

[[cascade]]
  layout = "home"
  [cascade._target]
    path = "/"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Allows line-breaks in markdown 
      unsafe = true
[minify]
  minifyOutput = true
  [minify.tdewolff.html]
    keepWhitespace = true
    keepEndTags = true
    keepDefaultAttrVals = false
    keepDocumentTags = true
