baseURL = "https://jack-bradshaw.com/"
languageCode = "en-us"
title = "Jack Bradshaw"
disableKinds = ["taxonomy", "term", "section"]

[params]
  description = "The collected works"
  googleAnalytics = "G-3LQFSGQLVV"

[[cascade]]
  layout = "home"
  [cascade._target]
    path = "/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Allows line-breaks in markdown 
      unsafe = true

[minify]
  minifyOutput = true
  [minify.tdewolff.html]
    keepWhitespace = true
    keepEndTags = true
    keepDefaultAttrVals = false
    keepDocumentTags = true
